### ISSUE TITLE
Can we get a way to sort the puzzles inside each meta alphabetically?

### ISSUE THREAD

**Issue by fezzik21** [Torgen/codex-blackboard#261]
Hi Mr. Rosart,  thank you for your excellent piece of tech.  My name is Adam, and I installed your server for our team, Stumped and Furious, to use for this year's hunt.  We're not a competitive team, but we did take it somewhat seriously and had 15-20 folks and solved 70-odd puzzles.  I made a few tweaks to it to support our needs, but I got stuck on something: one thing we desperately wanted was the ability to sort the puzzles alphabetically in each meta (instead of in the order they have been manually set to).  I've been trying to piece together how to make that change but I'm not too familiar with Meteor, Spacebar nor really CoffeeScript and I have failed miserably.  I didn't know how to contact you, but you're welcome to contact me out-of-band at shinyobject@gmail.com.  Thank you so much!  Even if you don't have time to help us please know that your software was amazing!  Thanks!

**Comment by Torgen** [comment]
1) Something like a toggle button that shows up in edit mode that lets you pick between manual and alphabetical?
2) Do you care about a bot command to change it, or is it ok to only be able to set it in the UI?
3) Are there other orders you expect to want? Time unlocked? Value of an arbitrary tag?
